# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bcc < Formula
  desc "Director-driven coding pipeline for autonomous agent loops."
  homepage "https://github.com/fgmacedo/buchecha"
  version "0.0.1-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc1/bcc_0.0.1-rc1_darwin_amd64.tar.gz"
      sha256 "3d16dfcae30dddf738435ed4365ff956756abaef7a68c6770369a57c9f2eb0a1"

      define_method(:install) do
        bin.install "bcc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc1/bcc_0.0.1-rc1_darwin_arm64.tar.gz"
      sha256 "22fa092a75a45734262e3040ba510ac71571b0944a772f1b0ad6e57eb37a513b"

      define_method(:install) do
        bin.install "bcc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc1/bcc_0.0.1-rc1_linux_amd64.tar.gz"
      sha256 "efe288c1b036e85f3c5b8571ebbd3cfc83f36287943616aad8516741dac5d5d7"
      define_method(:install) do
        bin.install "bcc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc1/bcc_0.0.1-rc1_linux_arm64.tar.gz"
      sha256 "8c23cd9705d461e54b06f2ace2a3f8e086520b297000d9552c720175f6497631"
      define_method(:install) do
        bin.install "bcc"
      end
    end
  end

  test do
    system "#{bin}/bcc", "--version"
  end
end
