# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buchecha < Formula
  desc "Director-driven coding pipeline for autonomous agent loops."
  homepage "https://github.com/fgmacedo/buchecha"
  version "0.0.1-rc2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc2/bcc_0.0.1-rc2_darwin_amd64.tar.gz"
      sha256 "ef2704b4a73b1f07ff9be57222f45e02d85f72f817cf60cd49fa998eb4c82a66"

      define_method(:install) do
        bin.install "bcc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc2/bcc_0.0.1-rc2_darwin_arm64.tar.gz"
      sha256 "314d7e513138cad96e4ea891c9f2f654714a4f92f2e97b4699853feb49b75427"

      define_method(:install) do
        bin.install "bcc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc2/bcc_0.0.1-rc2_linux_amd64.tar.gz"
      sha256 "c44349c617a19f3de9e949126624f72c04f29748bee709de8d6ff3f093ce6155"
      define_method(:install) do
        bin.install "bcc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fgmacedo/buchecha/releases/download/v0.0.1-rc2/bcc_0.0.1-rc2_linux_arm64.tar.gz"
      sha256 "8c9a1342a74ffc3b3b4dd5b8a3fdcc9677a3fb3e872475723787065af1b68e65"
      define_method(:install) do
        bin.install "bcc"
      end
    end
  end

  test do
    system "#{bin}/bcc", "--version"
  end
end
